### ISSUE TITLE
Support for T.Optional variant

### ISSUE THREAD

**Issue by EmilStenstrom** [hauntsaninja/no_implicit_optional#10]
Hi!

I have some code that uses the idiom:

```python
import typing as T

def test(param: T.Optional[str] = "hello"):
    ...
```

The command in this repo turns this into `Optional[T.Optional[str]]` and adds an unessesary import. I think this way of writing is fairly popular (?). If it is, would it be possible to add support for this variant too?

**Comment by hauntsaninja** [comment]
Thanks, released in 1.3
