### ISSUE TITLE
take multiple positional arguments?

### ISSUE THREAD

**Issue by asottile-sentry** [hauntsaninja/no_implicit_optional#13]
basically I would like to use `git ls-files -- '*.py' | xargs -P16 -n20 no_implicit_optional` but it only takes a single positional argument

```
$ no_implicit_optional tools/*.py
usage: no_implicit_optional [-h] [--use-union-or] path
no_implicit_optional: error: unrecognized arguments: tools/bump_action.py tools/devservices_healthcheck.py tools/docker_memory_check.py tools/flake8_plugin.py tools/freeze_requirements.py tools/lib.py tools/lint_requirements.py tools/pin_github_action.py
```

**Comment by hauntsaninja** [comment]
Added this, will make a release!

Note that the underlying libcst code already uses multiprocessing, so you probably don't want to be using parallel xargs
