### ISSUE TITLE
libcst._version raises ValueError: source code string cannot contain null byte 

### ISSUE THREAD

**Issue by kalebdfischer** [hauntsaninja/no_implicit_optional#2]
~~I'll open a PR momentarily with the fix, but the following is raised when attempting to run:~~

```Traceback (most recent call last):
  File ".../bin/no_implicit_optional", line 5, in <module>
    from no_implicit_optional import main
  File ".../lib/python3.9/site-packages/no_implicit_optional.py", line 6, in <module>
    import libcst as cst
  File ".../lib/python3.9/site-packages/libcst/__init__.py", line 215, in <module>
    from libcst._version import version as LIBCST_VERSION
ValueError: source code string cannot contain null byte
```
libcst version is 0.4.8

The issue is actually with libcst, so the issue can be closed. I was able to get no_implicit_optional running by editing the local environment copy of [libcst's \_\_init\_\_.py on line 216](https://github.com/Instagram/LibCST/blob/main/libcst/__init__.py#L216) from `except ImportError:` to `except (ImportError, ValueError):`

**Comment by hauntsaninja** [comment]
Thanks, sounds good. Seems like https://github.com/Instagram/LibCST/issues/817 is the issue filed on libcst
