### ISSUE TITLE
No need to transfer Any =None to Optional[Any] =None 

### ISSUE THREAD

**Issue by xiaoyanli-lyft** [hauntsaninja/no_implicit_optional#20]
I was checking and found this already been replied https://github.com/hauntsaninja/no_implicit_optional/issues/14

However, I test in mypy v1.5.1 in python3.8 env, the error already updated from Optional[Any] to Any. Should we also follow for consistency? Basically we don't need to change Any to be Optional[Any]
```
 $ mypy --implicit-optional before.py
before.py:3: error: Function is missing a return type annotation  [no-untyped-def]
before.py:4: note: Revealed type is "Union[Any, None]"
before.py:5: error: Item "None" of "Any | None" has no attribute "split"  [union-attr]
Found 2 errors in 1 file (checked 1 source file)
 $ mypy --implicit-optional after.py 
after.py:3: error: Function is missing a return type annotation  [no-untyped-def]
after.py:4: note: Revealed type is "Union[Any, None]"
after.py:5: error: Item "None" of "Any | None" has no attribute "split"  [union-attr]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by hauntsaninja** [comment]
Yeah, I think everything I said in #14 still holds true.

This codemod is about making sure behaviour is the same when you change from `--implicit-optional` to `--no-implicit-optional`, if you check the following file with `--no-implicit-optional` you do not get an error, which is a regression from when you check it with `--implicit-optional`:
```
from typing import Any, Optional

def f(x: Any = None):
    return x.split()
```
