### ISSUE TITLE
Unneed import Optional

### ISSUE THREAD

**Issue by xiaoyanli-lyft** [hauntsaninja/no_implicit_optional#21]
Testing some python3.8 codebase,
no_impilicit_optional still insert 
```
from typing import Optional
```
when code has
```
from __future__ import annotations
```

**Comment by hauntsaninja** [comment]
Thanks for the issue! If I understand the situation correctly, the symbol still needs to be imported for mypy to be able to resolve it. It also needs to be imported if you have runtime evaluation of type annotations.
