### ISSUE TITLE
Tool does not correctly respect typing.Annotated

### ISSUE THREAD

**Issue by silasary** [hauntsaninja/no_implicit_optional#3]
[typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) allows for annotations to have both a type annotation, and also additional data.

When encountered, the typing annotation is the first generic parameter, and any additional parameters are bonus data.

The tool currently doesn't acknowledge that, and wraps the whole Annotated annotation in an Optional.

Expected: 
```diff
-async def offending(param: Annotated[str, str.isdigit] = None) -> None:
+async def offending(param: Annotated[Optional[str], str.isdigit] = None) -> None:

async def good(param: Annotated[Optional[str], str.isdigit] = None) -> None:
```

Current Output:
```diff
-async def offending(param: Annotated[str, str.isdigit] = None) -> None:
+async def offending(param: Optional[Annotated[str, str.isdigit]] = None) -> None:

-async def good(param: Annotated[Optional[str], str.isdigit] = None) -> None:
+async def good(param: Optional[Annotated[Optional[str], str.isdigit]] = None) -> None:
```

**Comment by hauntsaninja** [comment]
Thanks! This should be fixed, just released v1.1
