### ISSUE TITLE
version 1.1 introduces TypeError

### ISSUE THREAD

**Issue by okasen** [hauntsaninja/no_implicit_optional#5]
Hi! I just attempted to run no_implicit_optional on a codebase, and I received this traceback:

```
Traceback (most recent call last):
  File "/Users/jenniferblack/.pyenv/versions/3.8.10/bin/no_implicit_optional", line 5, in <module>
    from no_implicit_optional import main
  File "/Users/jenniferblack/.pyenv/versions/3.8.10/lib/python3.8/site-packages/no_implicit_optional.py", line 102, in <module>
    ) -> tuple[bool, cst.BaseExpression]:
TypeError: 'type' object is not subscriptable
```

I attempted to run the codemod a few different ways, both in and out of a poetry venv, and on different paths ( "no_implicit_optional ." or the same command on explicit directories and files) and found no difference.

In case it's helpful, I'm running on an M1 MacBook. 

Version 1.0 works fine, for the record (and is quite helpful, thank you)

**Comment by hauntsaninja** [comment]
Thanks, fixed by https://github.com/hauntsaninja/no_implicit_optional/pull/6. Will make a new release soon
